FROM nginx:alpine

# Copy the NGINX configuration file
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copy SSL certificates
COPY nginx/certificate.crt /etc/ssl/certs/
COPY nginx/private.key /etc/ssl/private/

# Expose ports for HTTP and HTTPS
EXPOSE 80
EXPOSE 443

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
