version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket_backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: websocket_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certificate.crt:/etc/ssl/certs/certificate.crt:ro
      - ./nginx/private.key:/etc/ssl/private/private.key:ro
    depends_on:
      - backend
    restart: always
